languages:
  JavaScript: true

exclude_paths:
- ".gitignore"
- ".travis.yml"
- "LICENSE"
- "README.md"

engines:
  fixme:
    enabled: true
  coffeelint:
    enabled: true
  eslint:
    enabled: true

  nodesecurity:
    enabled: false

ratings:
  paths: []
